---
- project:
    name: restfuzz
    check:
      jobs:
        - tox-py35-f27
        - tox-pep8:
            nodeset:
              nodes:
                - name: container
                  label: f27-oci

    gate:
      jobs:
        - noop
